name:                one-liner-instances
version:             0.1.1.0
github:              "mstksg/one-liner-instances"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Generics-based implementations for common typeclasses
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  Provides generics-based implementations for common typeclasses using
  Generics.

  Please see the README on Github at <https://github.com/mstksg/one-liner-instances#readme>

dependencies:
- base >= 4.7 && < 5
- one-liner >= 0.9
- random

library:
  source-dirs: src
  exposed-modules:
  - Data.Bounded.OneLiner
  - Data.Monoid.OneLiner
  - Data.Ord.OneLiner
  - Numeric.OneLiner
  ghc-options: -Wall
